// Exceptions

// Exception Handling 


public class Hello {

    public static void main(String args[]) throws ClassNotFoundException {

        int i = 0;
        int j = 0;

        int arr[] = new int[5];


        // try and multiple catch -- try can't handle multiple statement as it jumps out of try once it founds an exception in a statement without going throw rest of the statement

        try 
        {
            j = 18 / i; // critical statement
            System.out.println(arr[0]);
            System.out.println(arr[5]);
        }
        catch(ArithmeticException e)
        {
            System.out.println("Cannot divide by zero");
        }
        catch(ArrayIndexOutOfBoundsException e) 
        {
            System.out.println("Stay in your Limits");
        }
        catch(Exception e) 
        {
            System.out.println("Please insert correct integer!!!" + e);
        }

        System.out.println(j);
        System.out.println("Bye");
    }
}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


// Exceptions

// Exception Handling 

// Exception throw keyword


public class Hello {

    public static void main(String args[]) throws ClassNotFoundException {

        int i = 0;
        int j = 0;

        // Exception throw keyword

        try 
        {
            j = 18 / i; // critical statement
            if(j==0)
                throw new ArithmeticException("I don't want to print zero");
            
        }
        catch(ArithmeticException e)
        {
            j = 18 / 1;
            System.out.println("that's the default output " + e);
        }
        catch(ArrayIndexOutOfBoundsException e) 
        {
            System.out.println("Stay in your Limits");
        }
        catch(Exception e) 
        {
            System.out.println("Please insert correct integer!!!" + e);
        }

        System.out.println(j);
        System.out.println("Bye");
    }
}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

// Exceptions

// Exception Handling 

// Exception throw keyword


public class Hello {

    public static void main(String args[]) throws ClassNotFoundException {

        int i = 0;
        int j = 0;

        // Exception throw keyword

        try 
        {
            j = 18 / i; // critical statement
            if(j==0)
                throw new ArithmeticException("I don't want to print zero");
            
        }
        catch(ArithmeticException e)
        {
            j = 18 / 1;
            System.out.println("that's the default output " + e);
        }
        catch(ArrayIndexOutOfBoundsException e) 
        {
            System.out.println("Stay in your Limits");
        }
        catch(Exception e) 
        {
            System.out.println("Please insert correct integer!!!" + e);
        }

        System.out.println(j);
        System.out.println("Bye");
    }
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

// Exceptions

// Exception Handling 

// throws Exception

class A 
{
    public void show() throws ClassNotFoundException
    {
        Class.forName("Calc");
    }
}

public class Hello {

    static {
        System.out.println("Class Loaded");
    }

    public static void main(String args[]) {

        A obj = new A();
        try {
            obj.show();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        
    }
}

